apiVersion: v1
kind: Service
metadata:
  name: jobportal-service
spec:
  selector:
    app: jobportal-pod
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobportal
  labels:
    app: jobportal-pod
spec:
  selector:
    matchLabels:
      app: jobportal-pod
  replicas: 2
  template:
    metadata:
      labels:
        app: jobportal-pod
    spec:
      containers:
      - name: jobportal-app
        image: docker.io/pravsp/galaxies:pyflask-jobportal
        imagePullPolicy: Always
        env:
        - name: FLASK_APP
          value: "jobportal"
        - name: FLASK_ENV
          value: "development"
        - name: FLASK_RUN_HOST
          value: "0.0.0.0"
        - name: FLASK_RUN_PORT
          value: "5000"
        - name: MONGO_HOST
          value: "localhost"
        - name: MONGO_PORT
          value: "27017"
        ports:
        - containerPort: 5000

      - name: jp-mongodb
        image: docker.io/mongo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 27017